/*
Gr4vy API

Testing PaymentServiceDefinitionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/FuturHealth/gr4vy-go-sdk"
)

func Test_openapi_PaymentServiceDefinitionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PaymentServiceDefinitionsAPIService CreatePaymentServiceDefinitionSession", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var paymentServiceDefinitionId string

		resp, httpRes, err := apiClient.PaymentServiceDefinitionsAPI.CreatePaymentServiceDefinitionSession(context.Background(), paymentServiceDefinitionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentServiceDefinitionsAPIService GetPaymentServiceDefinition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var paymentServiceDefinitionId string

		resp, httpRes, err := apiClient.PaymentServiceDefinitionsAPI.GetPaymentServiceDefinition(context.Background(), paymentServiceDefinitionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentServiceDefinitionsAPIService ListPaymentServiceDefinitions", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.PaymentServiceDefinitionsAPI.ListPaymentServiceDefinitions(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
