/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TransactionsReportSpecParamsFiltersCapturedAt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionsReportSpecParamsFiltersCapturedAt{}

// TransactionsReportSpecParamsFiltersCapturedAt The time window for when the transactions were captured to filter by.
type TransactionsReportSpecParamsFiltersCapturedAt struct {
	// The starting boundary for when the transactions were captured as either a date-time or date-time placeholder value.
	Start *string `json:"start,omitempty"`
	// The ending boundary for when the transactions were captured as either a date-time or date-time placeholder value.
	End *string `json:"end,omitempty"`
}

// NewTransactionsReportSpecParamsFiltersCapturedAt instantiates a new TransactionsReportSpecParamsFiltersCapturedAt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionsReportSpecParamsFiltersCapturedAt() *TransactionsReportSpecParamsFiltersCapturedAt {
	this := TransactionsReportSpecParamsFiltersCapturedAt{}
	return &this
}

// NewTransactionsReportSpecParamsFiltersCapturedAtWithDefaults instantiates a new TransactionsReportSpecParamsFiltersCapturedAt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionsReportSpecParamsFiltersCapturedAtWithDefaults() *TransactionsReportSpecParamsFiltersCapturedAt {
	this := TransactionsReportSpecParamsFiltersCapturedAt{}
	return &this
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *TransactionsReportSpecParamsFiltersCapturedAt) GetStart() string {
	if o == nil || IsNil(o.Start) {
		var ret string
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionsReportSpecParamsFiltersCapturedAt) GetStartOk() (*string, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *TransactionsReportSpecParamsFiltersCapturedAt) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given string and assigns it to the Start field.
func (o *TransactionsReportSpecParamsFiltersCapturedAt) SetStart(v string) {
	o.Start = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *TransactionsReportSpecParamsFiltersCapturedAt) GetEnd() string {
	if o == nil || IsNil(o.End) {
		var ret string
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionsReportSpecParamsFiltersCapturedAt) GetEndOk() (*string, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *TransactionsReportSpecParamsFiltersCapturedAt) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given string and assigns it to the End field.
func (o *TransactionsReportSpecParamsFiltersCapturedAt) SetEnd(v string) {
	o.End = &v
}

func (o TransactionsReportSpecParamsFiltersCapturedAt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionsReportSpecParamsFiltersCapturedAt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	return toSerialize, nil
}

type NullableTransactionsReportSpecParamsFiltersCapturedAt struct {
	value *TransactionsReportSpecParamsFiltersCapturedAt
	isSet bool
}

func (v NullableTransactionsReportSpecParamsFiltersCapturedAt) Get() *TransactionsReportSpecParamsFiltersCapturedAt {
	return v.value
}

func (v *NullableTransactionsReportSpecParamsFiltersCapturedAt) Set(val *TransactionsReportSpecParamsFiltersCapturedAt) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionsReportSpecParamsFiltersCapturedAt) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionsReportSpecParamsFiltersCapturedAt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionsReportSpecParamsFiltersCapturedAt(val *TransactionsReportSpecParamsFiltersCapturedAt) *NullableTransactionsReportSpecParamsFiltersCapturedAt {
	return &NullableTransactionsReportSpecParamsFiltersCapturedAt{value: val, isSet: true}
}

func (v NullableTransactionsReportSpecParamsFiltersCapturedAt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionsReportSpecParamsFiltersCapturedAt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


