/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AntiFraudWebhookEventContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AntiFraudWebhookEventContext{}

// AntiFraudWebhookEventContext Additional context for this event.
type AntiFraudWebhookEventContext struct {
	// The unique ID of the anti-fraud service used.
	AntiFraudServiceId *string `json:"anti_fraud_service_id,omitempty"`
	// The name of the anti-fraud service used.
	AntiFraudServiceName *string `json:"anti_fraud_service_name,omitempty"`
	// The anti-fraud service definition used.
	AntiFraudServiceDefinitionId *string `json:"anti_fraud_service_definition_id,omitempty"`
	// The external ID of the decision that's being updated.
	AntiFraudServiceCheckId *string `json:"anti_fraud_service_check_id,omitempty"`
	// The raw payload sent as a webhook.
	Content *string `json:"content,omitempty"`
	// The content type of the payload sent as a webhook.
	ContentType *string `json:"content_type,omitempty"`
	// The parsed decision response from the anti-fraud provider webhook.
	Decision *string `json:"decision,omitempty"`
	// Any comment that may have come with the webhook event.
	Comment *string `json:"comment,omitempty"`
}

// NewAntiFraudWebhookEventContext instantiates a new AntiFraudWebhookEventContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAntiFraudWebhookEventContext() *AntiFraudWebhookEventContext {
	this := AntiFraudWebhookEventContext{}
	return &this
}

// NewAntiFraudWebhookEventContextWithDefaults instantiates a new AntiFraudWebhookEventContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAntiFraudWebhookEventContextWithDefaults() *AntiFraudWebhookEventContext {
	this := AntiFraudWebhookEventContext{}
	return &this
}

// GetAntiFraudServiceId returns the AntiFraudServiceId field value if set, zero value otherwise.
func (o *AntiFraudWebhookEventContext) GetAntiFraudServiceId() string {
	if o == nil || IsNil(o.AntiFraudServiceId) {
		var ret string
		return ret
	}
	return *o.AntiFraudServiceId
}

// GetAntiFraudServiceIdOk returns a tuple with the AntiFraudServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AntiFraudWebhookEventContext) GetAntiFraudServiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.AntiFraudServiceId) {
		return nil, false
	}
	return o.AntiFraudServiceId, true
}

// HasAntiFraudServiceId returns a boolean if a field has been set.
func (o *AntiFraudWebhookEventContext) HasAntiFraudServiceId() bool {
	if o != nil && !IsNil(o.AntiFraudServiceId) {
		return true
	}

	return false
}

// SetAntiFraudServiceId gets a reference to the given string and assigns it to the AntiFraudServiceId field.
func (o *AntiFraudWebhookEventContext) SetAntiFraudServiceId(v string) {
	o.AntiFraudServiceId = &v
}

// GetAntiFraudServiceName returns the AntiFraudServiceName field value if set, zero value otherwise.
func (o *AntiFraudWebhookEventContext) GetAntiFraudServiceName() string {
	if o == nil || IsNil(o.AntiFraudServiceName) {
		var ret string
		return ret
	}
	return *o.AntiFraudServiceName
}

// GetAntiFraudServiceNameOk returns a tuple with the AntiFraudServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AntiFraudWebhookEventContext) GetAntiFraudServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.AntiFraudServiceName) {
		return nil, false
	}
	return o.AntiFraudServiceName, true
}

// HasAntiFraudServiceName returns a boolean if a field has been set.
func (o *AntiFraudWebhookEventContext) HasAntiFraudServiceName() bool {
	if o != nil && !IsNil(o.AntiFraudServiceName) {
		return true
	}

	return false
}

// SetAntiFraudServiceName gets a reference to the given string and assigns it to the AntiFraudServiceName field.
func (o *AntiFraudWebhookEventContext) SetAntiFraudServiceName(v string) {
	o.AntiFraudServiceName = &v
}

// GetAntiFraudServiceDefinitionId returns the AntiFraudServiceDefinitionId field value if set, zero value otherwise.
func (o *AntiFraudWebhookEventContext) GetAntiFraudServiceDefinitionId() string {
	if o == nil || IsNil(o.AntiFraudServiceDefinitionId) {
		var ret string
		return ret
	}
	return *o.AntiFraudServiceDefinitionId
}

// GetAntiFraudServiceDefinitionIdOk returns a tuple with the AntiFraudServiceDefinitionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AntiFraudWebhookEventContext) GetAntiFraudServiceDefinitionIdOk() (*string, bool) {
	if o == nil || IsNil(o.AntiFraudServiceDefinitionId) {
		return nil, false
	}
	return o.AntiFraudServiceDefinitionId, true
}

// HasAntiFraudServiceDefinitionId returns a boolean if a field has been set.
func (o *AntiFraudWebhookEventContext) HasAntiFraudServiceDefinitionId() bool {
	if o != nil && !IsNil(o.AntiFraudServiceDefinitionId) {
		return true
	}

	return false
}

// SetAntiFraudServiceDefinitionId gets a reference to the given string and assigns it to the AntiFraudServiceDefinitionId field.
func (o *AntiFraudWebhookEventContext) SetAntiFraudServiceDefinitionId(v string) {
	o.AntiFraudServiceDefinitionId = &v
}

// GetAntiFraudServiceCheckId returns the AntiFraudServiceCheckId field value if set, zero value otherwise.
func (o *AntiFraudWebhookEventContext) GetAntiFraudServiceCheckId() string {
	if o == nil || IsNil(o.AntiFraudServiceCheckId) {
		var ret string
		return ret
	}
	return *o.AntiFraudServiceCheckId
}

// GetAntiFraudServiceCheckIdOk returns a tuple with the AntiFraudServiceCheckId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AntiFraudWebhookEventContext) GetAntiFraudServiceCheckIdOk() (*string, bool) {
	if o == nil || IsNil(o.AntiFraudServiceCheckId) {
		return nil, false
	}
	return o.AntiFraudServiceCheckId, true
}

// HasAntiFraudServiceCheckId returns a boolean if a field has been set.
func (o *AntiFraudWebhookEventContext) HasAntiFraudServiceCheckId() bool {
	if o != nil && !IsNil(o.AntiFraudServiceCheckId) {
		return true
	}

	return false
}

// SetAntiFraudServiceCheckId gets a reference to the given string and assigns it to the AntiFraudServiceCheckId field.
func (o *AntiFraudWebhookEventContext) SetAntiFraudServiceCheckId(v string) {
	o.AntiFraudServiceCheckId = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *AntiFraudWebhookEventContext) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AntiFraudWebhookEventContext) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *AntiFraudWebhookEventContext) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *AntiFraudWebhookEventContext) SetContent(v string) {
	o.Content = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *AntiFraudWebhookEventContext) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AntiFraudWebhookEventContext) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *AntiFraudWebhookEventContext) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *AntiFraudWebhookEventContext) SetContentType(v string) {
	o.ContentType = &v
}

// GetDecision returns the Decision field value if set, zero value otherwise.
func (o *AntiFraudWebhookEventContext) GetDecision() string {
	if o == nil || IsNil(o.Decision) {
		var ret string
		return ret
	}
	return *o.Decision
}

// GetDecisionOk returns a tuple with the Decision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AntiFraudWebhookEventContext) GetDecisionOk() (*string, bool) {
	if o == nil || IsNil(o.Decision) {
		return nil, false
	}
	return o.Decision, true
}

// HasDecision returns a boolean if a field has been set.
func (o *AntiFraudWebhookEventContext) HasDecision() bool {
	if o != nil && !IsNil(o.Decision) {
		return true
	}

	return false
}

// SetDecision gets a reference to the given string and assigns it to the Decision field.
func (o *AntiFraudWebhookEventContext) SetDecision(v string) {
	o.Decision = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *AntiFraudWebhookEventContext) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AntiFraudWebhookEventContext) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *AntiFraudWebhookEventContext) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *AntiFraudWebhookEventContext) SetComment(v string) {
	o.Comment = &v
}

func (o AntiFraudWebhookEventContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AntiFraudWebhookEventContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AntiFraudServiceId) {
		toSerialize["anti_fraud_service_id"] = o.AntiFraudServiceId
	}
	if !IsNil(o.AntiFraudServiceName) {
		toSerialize["anti_fraud_service_name"] = o.AntiFraudServiceName
	}
	if !IsNil(o.AntiFraudServiceDefinitionId) {
		toSerialize["anti_fraud_service_definition_id"] = o.AntiFraudServiceDefinitionId
	}
	if !IsNil(o.AntiFraudServiceCheckId) {
		toSerialize["anti_fraud_service_check_id"] = o.AntiFraudServiceCheckId
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.ContentType) {
		toSerialize["content_type"] = o.ContentType
	}
	if !IsNil(o.Decision) {
		toSerialize["decision"] = o.Decision
	}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	return toSerialize, nil
}

type NullableAntiFraudWebhookEventContext struct {
	value *AntiFraudWebhookEventContext
	isSet bool
}

func (v NullableAntiFraudWebhookEventContext) Get() *AntiFraudWebhookEventContext {
	return v.value
}

func (v *NullableAntiFraudWebhookEventContext) Set(val *AntiFraudWebhookEventContext) {
	v.value = val
	v.isSet = true
}

func (v NullableAntiFraudWebhookEventContext) IsSet() bool {
	return v.isSet
}

func (v *NullableAntiFraudWebhookEventContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAntiFraudWebhookEventContext(val *AntiFraudWebhookEventContext) *NullableAntiFraudWebhookEventContext {
	return &NullableAntiFraudWebhookEventContext{value: val, isSet: true}
}

func (v NullableAntiFraudWebhookEventContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAntiFraudWebhookEventContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


