/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NetworkTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkTokenRequest{}

// NetworkTokenRequest Request body for provision a network token.
type NetworkTokenRequest struct {
	// The 3 or 4 digit security code often found on the card. This often referred to as the CVV or CVD.  The security code can only be set if the stored payment method represents a card.
	SecurityCode NullableString `json:"security_code,omitempty" validate:"regexp=^\\\\d{3,4}$"`
	// Defines if the request is merchant initiated or not.
	MerchantInitiated bool `json:"merchant_initiated"`
	// Defines if the request is a subsequent of another request or not.
	IsSubsequentPayment bool `json:"is_subsequent_payment"`
}

type _NetworkTokenRequest NetworkTokenRequest

// NewNetworkTokenRequest instantiates a new NetworkTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkTokenRequest(merchantInitiated bool, isSubsequentPayment bool) *NetworkTokenRequest {
	this := NetworkTokenRequest{}
	this.MerchantInitiated = merchantInitiated
	this.IsSubsequentPayment = isSubsequentPayment
	return &this
}

// NewNetworkTokenRequestWithDefaults instantiates a new NetworkTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkTokenRequestWithDefaults() *NetworkTokenRequest {
	this := NetworkTokenRequest{}
	return &this
}

// GetSecurityCode returns the SecurityCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkTokenRequest) GetSecurityCode() string {
	if o == nil || IsNil(o.SecurityCode.Get()) {
		var ret string
		return ret
	}
	return *o.SecurityCode.Get()
}

// GetSecurityCodeOk returns a tuple with the SecurityCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkTokenRequest) GetSecurityCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecurityCode.Get(), o.SecurityCode.IsSet()
}

// HasSecurityCode returns a boolean if a field has been set.
func (o *NetworkTokenRequest) HasSecurityCode() bool {
	if o != nil && o.SecurityCode.IsSet() {
		return true
	}

	return false
}

// SetSecurityCode gets a reference to the given NullableString and assigns it to the SecurityCode field.
func (o *NetworkTokenRequest) SetSecurityCode(v string) {
	o.SecurityCode.Set(&v)
}
// SetSecurityCodeNil sets the value for SecurityCode to be an explicit nil
func (o *NetworkTokenRequest) SetSecurityCodeNil() {
	o.SecurityCode.Set(nil)
}

// UnsetSecurityCode ensures that no value is present for SecurityCode, not even an explicit nil
func (o *NetworkTokenRequest) UnsetSecurityCode() {
	o.SecurityCode.Unset()
}

// GetMerchantInitiated returns the MerchantInitiated field value
func (o *NetworkTokenRequest) GetMerchantInitiated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.MerchantInitiated
}

// GetMerchantInitiatedOk returns a tuple with the MerchantInitiated field value
// and a boolean to check if the value has been set.
func (o *NetworkTokenRequest) GetMerchantInitiatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantInitiated, true
}

// SetMerchantInitiated sets field value
func (o *NetworkTokenRequest) SetMerchantInitiated(v bool) {
	o.MerchantInitiated = v
}

// GetIsSubsequentPayment returns the IsSubsequentPayment field value
func (o *NetworkTokenRequest) GetIsSubsequentPayment() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsSubsequentPayment
}

// GetIsSubsequentPaymentOk returns a tuple with the IsSubsequentPayment field value
// and a boolean to check if the value has been set.
func (o *NetworkTokenRequest) GetIsSubsequentPaymentOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsSubsequentPayment, true
}

// SetIsSubsequentPayment sets field value
func (o *NetworkTokenRequest) SetIsSubsequentPayment(v bool) {
	o.IsSubsequentPayment = v
}

func (o NetworkTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.SecurityCode.IsSet() {
		toSerialize["security_code"] = o.SecurityCode.Get()
	}
	toSerialize["merchant_initiated"] = o.MerchantInitiated
	toSerialize["is_subsequent_payment"] = o.IsSubsequentPayment
	return toSerialize, nil
}

func (o *NetworkTokenRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"merchant_initiated",
		"is_subsequent_payment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkTokenRequest := _NetworkTokenRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetworkTokenRequest)

	if err != nil {
		return err
	}

	*o = NetworkTokenRequest(varNetworkTokenRequest)

	return err
}

type NullableNetworkTokenRequest struct {
	value *NetworkTokenRequest
	isSet bool
}

func (v NullableNetworkTokenRequest) Get() *NetworkTokenRequest {
	return v.value
}

func (v *NullableNetworkTokenRequest) Set(val *NetworkTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkTokenRequest(val *NetworkTokenRequest) *NullableNetworkTokenRequest {
	return &NullableNetworkTokenRequest{value: val, isSet: true}
}

func (v NullableNetworkTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


