/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ThreeDSecureDataV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThreeDSecureDataV1{}

// ThreeDSecureDataV1 struct for ThreeDSecureDataV1
type ThreeDSecureDataV1 struct {
	// The cardholder authentication value or AAV.
	Cavv string `json:"cavv"`
	// The electronic commerce indicator for the 3DS transaction.
	Eci string `json:"eci" validate:"regexp=^0?\\\\d$"`
	// The version of 3-D Secure that was used.
	Version string `json:"version" validate:"regexp=^[1-2].?[\\\\d+.?]{0,3}$"`
	// For 3-D Secure version 1, the enrolment response. For 3-D Secure version , the transaction status from the `ARes`.
	DirectoryResponse string `json:"directory_response"`
	// The scheme/brand of the card that is used for 3-D Secure.
	Scheme NullableString `json:"scheme,omitempty"`
	// The response for the 3DS authentication call.
	AuthenticationResponse string `json:"authentication_response"`
	// The CAVV algorithm used.
	CavvAlgorithm string `json:"cavv_algorithm"`
	// The transaction identifier.
	Xid string `json:"xid"`
}

type _ThreeDSecureDataV1 ThreeDSecureDataV1

// NewThreeDSecureDataV1 instantiates a new ThreeDSecureDataV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThreeDSecureDataV1(cavv string, eci string, version string, directoryResponse string, authenticationResponse string, cavvAlgorithm string, xid string) *ThreeDSecureDataV1 {
	this := ThreeDSecureDataV1{}
	this.Cavv = cavv
	this.Eci = eci
	this.Version = version
	this.DirectoryResponse = directoryResponse
	this.AuthenticationResponse = authenticationResponse
	this.CavvAlgorithm = cavvAlgorithm
	this.Xid = xid
	return &this
}

// NewThreeDSecureDataV1WithDefaults instantiates a new ThreeDSecureDataV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThreeDSecureDataV1WithDefaults() *ThreeDSecureDataV1 {
	this := ThreeDSecureDataV1{}
	return &this
}

// GetCavv returns the Cavv field value
func (o *ThreeDSecureDataV1) GetCavv() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cavv
}

// GetCavvOk returns a tuple with the Cavv field value
// and a boolean to check if the value has been set.
func (o *ThreeDSecureDataV1) GetCavvOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cavv, true
}

// SetCavv sets field value
func (o *ThreeDSecureDataV1) SetCavv(v string) {
	o.Cavv = v
}

// GetEci returns the Eci field value
func (o *ThreeDSecureDataV1) GetEci() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Eci
}

// GetEciOk returns a tuple with the Eci field value
// and a boolean to check if the value has been set.
func (o *ThreeDSecureDataV1) GetEciOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Eci, true
}

// SetEci sets field value
func (o *ThreeDSecureDataV1) SetEci(v string) {
	o.Eci = v
}

// GetVersion returns the Version field value
func (o *ThreeDSecureDataV1) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ThreeDSecureDataV1) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ThreeDSecureDataV1) SetVersion(v string) {
	o.Version = v
}

// GetDirectoryResponse returns the DirectoryResponse field value
func (o *ThreeDSecureDataV1) GetDirectoryResponse() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DirectoryResponse
}

// GetDirectoryResponseOk returns a tuple with the DirectoryResponse field value
// and a boolean to check if the value has been set.
func (o *ThreeDSecureDataV1) GetDirectoryResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DirectoryResponse, true
}

// SetDirectoryResponse sets field value
func (o *ThreeDSecureDataV1) SetDirectoryResponse(v string) {
	o.DirectoryResponse = v
}

// GetScheme returns the Scheme field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ThreeDSecureDataV1) GetScheme() string {
	if o == nil || IsNil(o.Scheme.Get()) {
		var ret string
		return ret
	}
	return *o.Scheme.Get()
}

// GetSchemeOk returns a tuple with the Scheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ThreeDSecureDataV1) GetSchemeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scheme.Get(), o.Scheme.IsSet()
}

// HasScheme returns a boolean if a field has been set.
func (o *ThreeDSecureDataV1) HasScheme() bool {
	if o != nil && o.Scheme.IsSet() {
		return true
	}

	return false
}

// SetScheme gets a reference to the given NullableString and assigns it to the Scheme field.
func (o *ThreeDSecureDataV1) SetScheme(v string) {
	o.Scheme.Set(&v)
}
// SetSchemeNil sets the value for Scheme to be an explicit nil
func (o *ThreeDSecureDataV1) SetSchemeNil() {
	o.Scheme.Set(nil)
}

// UnsetScheme ensures that no value is present for Scheme, not even an explicit nil
func (o *ThreeDSecureDataV1) UnsetScheme() {
	o.Scheme.Unset()
}

// GetAuthenticationResponse returns the AuthenticationResponse field value
func (o *ThreeDSecureDataV1) GetAuthenticationResponse() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthenticationResponse
}

// GetAuthenticationResponseOk returns a tuple with the AuthenticationResponse field value
// and a boolean to check if the value has been set.
func (o *ThreeDSecureDataV1) GetAuthenticationResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationResponse, true
}

// SetAuthenticationResponse sets field value
func (o *ThreeDSecureDataV1) SetAuthenticationResponse(v string) {
	o.AuthenticationResponse = v
}

// GetCavvAlgorithm returns the CavvAlgorithm field value
func (o *ThreeDSecureDataV1) GetCavvAlgorithm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CavvAlgorithm
}

// GetCavvAlgorithmOk returns a tuple with the CavvAlgorithm field value
// and a boolean to check if the value has been set.
func (o *ThreeDSecureDataV1) GetCavvAlgorithmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CavvAlgorithm, true
}

// SetCavvAlgorithm sets field value
func (o *ThreeDSecureDataV1) SetCavvAlgorithm(v string) {
	o.CavvAlgorithm = v
}

// GetXid returns the Xid field value
func (o *ThreeDSecureDataV1) GetXid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Xid
}

// GetXidOk returns a tuple with the Xid field value
// and a boolean to check if the value has been set.
func (o *ThreeDSecureDataV1) GetXidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Xid, true
}

// SetXid sets field value
func (o *ThreeDSecureDataV1) SetXid(v string) {
	o.Xid = v
}

func (o ThreeDSecureDataV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThreeDSecureDataV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cavv"] = o.Cavv
	toSerialize["eci"] = o.Eci
	toSerialize["version"] = o.Version
	toSerialize["directory_response"] = o.DirectoryResponse
	if o.Scheme.IsSet() {
		toSerialize["scheme"] = o.Scheme.Get()
	}
	toSerialize["authentication_response"] = o.AuthenticationResponse
	toSerialize["cavv_algorithm"] = o.CavvAlgorithm
	toSerialize["xid"] = o.Xid
	return toSerialize, nil
}

func (o *ThreeDSecureDataV1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cavv",
		"eci",
		"version",
		"directory_response",
		"authentication_response",
		"cavv_algorithm",
		"xid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varThreeDSecureDataV1 := _ThreeDSecureDataV1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varThreeDSecureDataV1)

	if err != nil {
		return err
	}

	*o = ThreeDSecureDataV1(varThreeDSecureDataV1)

	return err
}

type NullableThreeDSecureDataV1 struct {
	value *ThreeDSecureDataV1
	isSet bool
}

func (v NullableThreeDSecureDataV1) Get() *ThreeDSecureDataV1 {
	return v.value
}

func (v *NullableThreeDSecureDataV1) Set(val *ThreeDSecureDataV1) {
	v.value = val
	v.isSet = true
}

func (v NullableThreeDSecureDataV1) IsSet() bool {
	return v.isSet
}

func (v *NullableThreeDSecureDataV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThreeDSecureDataV1(val *ThreeDSecureDataV1) *NullableThreeDSecureDataV1 {
	return &NullableThreeDSecureDataV1{value: val, isSet: true}
}

func (v NullableThreeDSecureDataV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThreeDSecureDataV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


