/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentServiceRequestReportingFieldsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentServiceRequestReportingFieldsInner{}

// PaymentServiceRequestReportingFieldsInner A key-value pair that represents a reporting field defined in the definition for this payment service.
type PaymentServiceRequestReportingFieldsInner struct {
	// The key of the field to set a value for.
	Key string `json:"key"`
	// The value of a field to set.
	Value string `json:"value"`
}

type _PaymentServiceRequestReportingFieldsInner PaymentServiceRequestReportingFieldsInner

// NewPaymentServiceRequestReportingFieldsInner instantiates a new PaymentServiceRequestReportingFieldsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentServiceRequestReportingFieldsInner(key string, value string) *PaymentServiceRequestReportingFieldsInner {
	this := PaymentServiceRequestReportingFieldsInner{}
	this.Key = key
	this.Value = value
	return &this
}

// NewPaymentServiceRequestReportingFieldsInnerWithDefaults instantiates a new PaymentServiceRequestReportingFieldsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentServiceRequestReportingFieldsInnerWithDefaults() *PaymentServiceRequestReportingFieldsInner {
	this := PaymentServiceRequestReportingFieldsInner{}
	return &this
}

// GetKey returns the Key field value
func (o *PaymentServiceRequestReportingFieldsInner) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *PaymentServiceRequestReportingFieldsInner) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *PaymentServiceRequestReportingFieldsInner) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *PaymentServiceRequestReportingFieldsInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *PaymentServiceRequestReportingFieldsInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *PaymentServiceRequestReportingFieldsInner) SetValue(v string) {
	o.Value = v
}

func (o PaymentServiceRequestReportingFieldsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentServiceRequestReportingFieldsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *PaymentServiceRequestReportingFieldsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentServiceRequestReportingFieldsInner := _PaymentServiceRequestReportingFieldsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentServiceRequestReportingFieldsInner)

	if err != nil {
		return err
	}

	*o = PaymentServiceRequestReportingFieldsInner(varPaymentServiceRequestReportingFieldsInner)

	return err
}

type NullablePaymentServiceRequestReportingFieldsInner struct {
	value *PaymentServiceRequestReportingFieldsInner
	isSet bool
}

func (v NullablePaymentServiceRequestReportingFieldsInner) Get() *PaymentServiceRequestReportingFieldsInner {
	return v.value
}

func (v *NullablePaymentServiceRequestReportingFieldsInner) Set(val *PaymentServiceRequestReportingFieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentServiceRequestReportingFieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentServiceRequestReportingFieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentServiceRequestReportingFieldsInner(val *PaymentServiceRequestReportingFieldsInner) *NullablePaymentServiceRequestReportingFieldsInner {
	return &NullablePaymentServiceRequestReportingFieldsInner{value: val, isSet: true}
}

func (v NullablePaymentServiceRequestReportingFieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentServiceRequestReportingFieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


