/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TransactionRetriesReportSpecParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionRetriesReportSpecParams{}

// TransactionRetriesReportSpecParams Parameters used to configure the report.
type TransactionRetriesReportSpecParams struct {
	Filters *TransactionRetriesReportSpecParamsFilters `json:"filters,omitempty"`
}

// NewTransactionRetriesReportSpecParams instantiates a new TransactionRetriesReportSpecParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionRetriesReportSpecParams() *TransactionRetriesReportSpecParams {
	this := TransactionRetriesReportSpecParams{}
	return &this
}

// NewTransactionRetriesReportSpecParamsWithDefaults instantiates a new TransactionRetriesReportSpecParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionRetriesReportSpecParamsWithDefaults() *TransactionRetriesReportSpecParams {
	this := TransactionRetriesReportSpecParams{}
	return &this
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *TransactionRetriesReportSpecParams) GetFilters() TransactionRetriesReportSpecParamsFilters {
	if o == nil || IsNil(o.Filters) {
		var ret TransactionRetriesReportSpecParamsFilters
		return ret
	}
	return *o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRetriesReportSpecParams) GetFiltersOk() (*TransactionRetriesReportSpecParamsFilters, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *TransactionRetriesReportSpecParams) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given TransactionRetriesReportSpecParamsFilters and assigns it to the Filters field.
func (o *TransactionRetriesReportSpecParams) SetFilters(v TransactionRetriesReportSpecParamsFilters) {
	o.Filters = &v
}

func (o TransactionRetriesReportSpecParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionRetriesReportSpecParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	return toSerialize, nil
}

type NullableTransactionRetriesReportSpecParams struct {
	value *TransactionRetriesReportSpecParams
	isSet bool
}

func (v NullableTransactionRetriesReportSpecParams) Get() *TransactionRetriesReportSpecParams {
	return v.value
}

func (v *NullableTransactionRetriesReportSpecParams) Set(val *TransactionRetriesReportSpecParams) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionRetriesReportSpecParams) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionRetriesReportSpecParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionRetriesReportSpecParams(val *TransactionRetriesReportSpecParams) *NullableTransactionRetriesReportSpecParams {
	return &NullableTransactionRetriesReportSpecParams{value: val, isSet: true}
}

func (v NullableTransactionRetriesReportSpecParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionRetriesReportSpecParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


