/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConnectionOptionsPaypalPaypalAdditionalDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionOptionsPaypalPaypalAdditionalDataInner{}

// ConnectionOptionsPaypalPaypalAdditionalDataInner struct for ConnectionOptionsPaypalPaypalAdditionalDataInner
type ConnectionOptionsPaypalPaypalAdditionalDataInner struct {
	Key *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewConnectionOptionsPaypalPaypalAdditionalDataInner instantiates a new ConnectionOptionsPaypalPaypalAdditionalDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionOptionsPaypalPaypalAdditionalDataInner() *ConnectionOptionsPaypalPaypalAdditionalDataInner {
	this := ConnectionOptionsPaypalPaypalAdditionalDataInner{}
	return &this
}

// NewConnectionOptionsPaypalPaypalAdditionalDataInnerWithDefaults instantiates a new ConnectionOptionsPaypalPaypalAdditionalDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionOptionsPaypalPaypalAdditionalDataInnerWithDefaults() *ConnectionOptionsPaypalPaypalAdditionalDataInner {
	this := ConnectionOptionsPaypalPaypalAdditionalDataInner{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ConnectionOptionsPaypalPaypalAdditionalDataInner) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionOptionsPaypalPaypalAdditionalDataInner) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ConnectionOptionsPaypalPaypalAdditionalDataInner) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ConnectionOptionsPaypalPaypalAdditionalDataInner) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ConnectionOptionsPaypalPaypalAdditionalDataInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionOptionsPaypalPaypalAdditionalDataInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ConnectionOptionsPaypalPaypalAdditionalDataInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ConnectionOptionsPaypalPaypalAdditionalDataInner) SetValue(v string) {
	o.Value = &v
}

func (o ConnectionOptionsPaypalPaypalAdditionalDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionOptionsPaypalPaypalAdditionalDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableConnectionOptionsPaypalPaypalAdditionalDataInner struct {
	value *ConnectionOptionsPaypalPaypalAdditionalDataInner
	isSet bool
}

func (v NullableConnectionOptionsPaypalPaypalAdditionalDataInner) Get() *ConnectionOptionsPaypalPaypalAdditionalDataInner {
	return v.value
}

func (v *NullableConnectionOptionsPaypalPaypalAdditionalDataInner) Set(val *ConnectionOptionsPaypalPaypalAdditionalDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionOptionsPaypalPaypalAdditionalDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionOptionsPaypalPaypalAdditionalDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionOptionsPaypalPaypalAdditionalDataInner(val *ConnectionOptionsPaypalPaypalAdditionalDataInner) *NullableConnectionOptionsPaypalPaypalAdditionalDataInner {
	return &NullableConnectionOptionsPaypalPaypalAdditionalDataInner{value: val, isSet: true}
}

func (v NullableConnectionOptionsPaypalPaypalAdditionalDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionOptionsPaypalPaypalAdditionalDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


