/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PayoutStoredCardRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutStoredCardRequest{}

// PayoutStoredCardRequest Stored card reference.
type PayoutStoredCardRequest struct {
	// The method to use.
	Method string `json:"method"`
	// The ID of the stored payment method.
	Id string `json:"id"`
}

type _PayoutStoredCardRequest PayoutStoredCardRequest

// NewPayoutStoredCardRequest instantiates a new PayoutStoredCardRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutStoredCardRequest(method string, id string) *PayoutStoredCardRequest {
	this := PayoutStoredCardRequest{}
	this.Method = method
	this.Id = id
	return &this
}

// NewPayoutStoredCardRequestWithDefaults instantiates a new PayoutStoredCardRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutStoredCardRequestWithDefaults() *PayoutStoredCardRequest {
	this := PayoutStoredCardRequest{}
	return &this
}

// GetMethod returns the Method field value
func (o *PayoutStoredCardRequest) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *PayoutStoredCardRequest) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *PayoutStoredCardRequest) SetMethod(v string) {
	o.Method = v
}

// GetId returns the Id field value
func (o *PayoutStoredCardRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PayoutStoredCardRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PayoutStoredCardRequest) SetId(v string) {
	o.Id = v
}

func (o PayoutStoredCardRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutStoredCardRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["method"] = o.Method
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *PayoutStoredCardRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"method",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPayoutStoredCardRequest := _PayoutStoredCardRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPayoutStoredCardRequest)

	if err != nil {
		return err
	}

	*o = PayoutStoredCardRequest(varPayoutStoredCardRequest)

	return err
}

type NullablePayoutStoredCardRequest struct {
	value *PayoutStoredCardRequest
	isSet bool
}

func (v NullablePayoutStoredCardRequest) Get() *PayoutStoredCardRequest {
	return v.value
}

func (v *NullablePayoutStoredCardRequest) Set(val *PayoutStoredCardRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutStoredCardRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutStoredCardRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutStoredCardRequest(val *PayoutStoredCardRequest) *NullablePayoutStoredCardRequest {
	return &NullablePayoutStoredCardRequest{value: val, isSet: true}
}

func (v NullablePayoutStoredCardRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutStoredCardRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


