/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GiftCardBalanceStoredRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GiftCardBalanceStoredRequest{}

// GiftCardBalanceStoredRequest Check the balance for a stored gift card.
type GiftCardBalanceStoredRequest struct {
	// The ID of the gift card to check a balance for.
	Id string `json:"id"`
}

type _GiftCardBalanceStoredRequest GiftCardBalanceStoredRequest

// NewGiftCardBalanceStoredRequest instantiates a new GiftCardBalanceStoredRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGiftCardBalanceStoredRequest(id string) *GiftCardBalanceStoredRequest {
	this := GiftCardBalanceStoredRequest{}
	this.Id = id
	return &this
}

// NewGiftCardBalanceStoredRequestWithDefaults instantiates a new GiftCardBalanceStoredRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGiftCardBalanceStoredRequestWithDefaults() *GiftCardBalanceStoredRequest {
	this := GiftCardBalanceStoredRequest{}
	return &this
}

// GetId returns the Id field value
func (o *GiftCardBalanceStoredRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GiftCardBalanceStoredRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GiftCardBalanceStoredRequest) SetId(v string) {
	o.Id = v
}

func (o GiftCardBalanceStoredRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GiftCardBalanceStoredRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *GiftCardBalanceStoredRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGiftCardBalanceStoredRequest := _GiftCardBalanceStoredRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGiftCardBalanceStoredRequest)

	if err != nil {
		return err
	}

	*o = GiftCardBalanceStoredRequest(varGiftCardBalanceStoredRequest)

	return err
}

type NullableGiftCardBalanceStoredRequest struct {
	value *GiftCardBalanceStoredRequest
	isSet bool
}

func (v NullableGiftCardBalanceStoredRequest) Get() *GiftCardBalanceStoredRequest {
	return v.value
}

func (v *NullableGiftCardBalanceStoredRequest) Set(val *GiftCardBalanceStoredRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGiftCardBalanceStoredRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGiftCardBalanceStoredRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGiftCardBalanceStoredRequest(val *GiftCardBalanceStoredRequest) *NullableGiftCardBalanceStoredRequest {
	return &NullableGiftCardBalanceStoredRequest{value: val, isSet: true}
}

func (v NullableGiftCardBalanceStoredRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGiftCardBalanceStoredRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


