/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PaymentMethodDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentMethodDefinition{}

// PaymentMethodDefinition Definitions of a payment method including icon, label, etc.
type PaymentMethodDefinition struct {
	// The mode of this payment method.
	Id *string `json:"id,omitempty"`
	// The icon for this payment method.
	IconUrl *string `json:"icon_url,omitempty"`
	// The display name of this payment method.
	DisplayName *string `json:"display_name,omitempty"`
	// The long display name of this payment method.
	LongDisplayName *string `json:"long_display_name,omitempty"`
	// The method, or type, for this payment method.
	Method *string `json:"method,omitempty"`
}

// NewPaymentMethodDefinition instantiates a new PaymentMethodDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentMethodDefinition() *PaymentMethodDefinition {
	this := PaymentMethodDefinition{}
	return &this
}

// NewPaymentMethodDefinitionWithDefaults instantiates a new PaymentMethodDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentMethodDefinitionWithDefaults() *PaymentMethodDefinition {
	this := PaymentMethodDefinition{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PaymentMethodDefinition) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodDefinition) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PaymentMethodDefinition) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PaymentMethodDefinition) SetId(v string) {
	o.Id = &v
}

// GetIconUrl returns the IconUrl field value if set, zero value otherwise.
func (o *PaymentMethodDefinition) GetIconUrl() string {
	if o == nil || IsNil(o.IconUrl) {
		var ret string
		return ret
	}
	return *o.IconUrl
}

// GetIconUrlOk returns a tuple with the IconUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodDefinition) GetIconUrlOk() (*string, bool) {
	if o == nil || IsNil(o.IconUrl) {
		return nil, false
	}
	return o.IconUrl, true
}

// HasIconUrl returns a boolean if a field has been set.
func (o *PaymentMethodDefinition) HasIconUrl() bool {
	if o != nil && !IsNil(o.IconUrl) {
		return true
	}

	return false
}

// SetIconUrl gets a reference to the given string and assigns it to the IconUrl field.
func (o *PaymentMethodDefinition) SetIconUrl(v string) {
	o.IconUrl = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *PaymentMethodDefinition) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodDefinition) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *PaymentMethodDefinition) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *PaymentMethodDefinition) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetLongDisplayName returns the LongDisplayName field value if set, zero value otherwise.
func (o *PaymentMethodDefinition) GetLongDisplayName() string {
	if o == nil || IsNil(o.LongDisplayName) {
		var ret string
		return ret
	}
	return *o.LongDisplayName
}

// GetLongDisplayNameOk returns a tuple with the LongDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodDefinition) GetLongDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.LongDisplayName) {
		return nil, false
	}
	return o.LongDisplayName, true
}

// HasLongDisplayName returns a boolean if a field has been set.
func (o *PaymentMethodDefinition) HasLongDisplayName() bool {
	if o != nil && !IsNil(o.LongDisplayName) {
		return true
	}

	return false
}

// SetLongDisplayName gets a reference to the given string and assigns it to the LongDisplayName field.
func (o *PaymentMethodDefinition) SetLongDisplayName(v string) {
	o.LongDisplayName = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *PaymentMethodDefinition) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodDefinition) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *PaymentMethodDefinition) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *PaymentMethodDefinition) SetMethod(v string) {
	o.Method = &v
}

func (o PaymentMethodDefinition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentMethodDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IconUrl) {
		toSerialize["icon_url"] = o.IconUrl
	}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.LongDisplayName) {
		toSerialize["long_display_name"] = o.LongDisplayName
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	return toSerialize, nil
}

type NullablePaymentMethodDefinition struct {
	value *PaymentMethodDefinition
	isSet bool
}

func (v NullablePaymentMethodDefinition) Get() *PaymentMethodDefinition {
	return v.value
}

func (v *NullablePaymentMethodDefinition) Set(val *PaymentMethodDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentMethodDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentMethodDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentMethodDefinition(val *PaymentMethodDefinition) *NullablePaymentMethodDefinition {
	return &NullablePaymentMethodDefinition{value: val, isSet: true}
}

func (v NullablePaymentMethodDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentMethodDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


