/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DigitalWallets type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DigitalWallets{}

// DigitalWallets A list of registered digital wallets.
type DigitalWallets struct {
	// A list of registered digital wallets.
	Items []DigitalWallet `json:"items,omitempty"`
}

// NewDigitalWallets instantiates a new DigitalWallets object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDigitalWallets() *DigitalWallets {
	this := DigitalWallets{}
	return &this
}

// NewDigitalWalletsWithDefaults instantiates a new DigitalWallets object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDigitalWalletsWithDefaults() *DigitalWallets {
	this := DigitalWallets{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *DigitalWallets) GetItems() []DigitalWallet {
	if o == nil || IsNil(o.Items) {
		var ret []DigitalWallet
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DigitalWallets) GetItemsOk() ([]DigitalWallet, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *DigitalWallets) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []DigitalWallet and assigns it to the Items field.
func (o *DigitalWallets) SetItems(v []DigitalWallet) {
	o.Items = v
}

func (o DigitalWallets) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DigitalWallets) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableDigitalWallets struct {
	value *DigitalWallets
	isSet bool
}

func (v NullableDigitalWallets) Get() *DigitalWallets {
	return v.value
}

func (v *NullableDigitalWallets) Set(val *DigitalWallets) {
	v.value = val
	v.isSet = true
}

func (v NullableDigitalWallets) IsSet() bool {
	return v.isSet
}

func (v *NullableDigitalWallets) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDigitalWallets(val *DigitalWallets) *NullableDigitalWallets {
	return &NullableDigitalWallets{value: val, isSet: true}
}

func (v NullableDigitalWallets) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDigitalWallets) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


