/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RedirectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RedirectRequest{}

// RedirectRequest Details to register a new redirect payment method.
type RedirectRequest struct {
	// The method to use, this can be any of the methods that support redirect requests.
	Method string `json:"method"`
	// The redirect URL to redirect a buyer to after they have authorized their transaction.
	RedirectUrl string `json:"redirect_url"`
	// The ISO-4217 currency code to use this payment method for. This is used to select the payment service to use.
	Currency string `json:"currency"`
	// The 2-letter ISO code of the country to use this payment method for. This is used to select the payment service to use.
	Country string `json:"country"`
	// An external identifier that can be used to match the account against your own records.
	ExternalIdentifier NullableString `json:"external_identifier,omitempty"`
	// The ID of the buyer to associate this payment method to. If this field is provided then the `buyer_external_identifier` field needs to be unset.
	BuyerId *string `json:"buyer_id,omitempty"`
	// The `external_identifier` of the buyer to associate this payment method to. If this field is provided then the `buyer_id` field needs to be unset.
	BuyerExternalIdentifier *string `json:"buyer_external_identifier,omitempty"`
}

type _RedirectRequest RedirectRequest

// NewRedirectRequest instantiates a new RedirectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRedirectRequest(method string, redirectUrl string, currency string, country string) *RedirectRequest {
	this := RedirectRequest{}
	this.Method = method
	this.RedirectUrl = redirectUrl
	this.Currency = currency
	this.Country = country
	return &this
}

// NewRedirectRequestWithDefaults instantiates a new RedirectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRedirectRequestWithDefaults() *RedirectRequest {
	this := RedirectRequest{}
	return &this
}

// GetMethod returns the Method field value
func (o *RedirectRequest) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *RedirectRequest) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *RedirectRequest) SetMethod(v string) {
	o.Method = v
}

// GetRedirectUrl returns the RedirectUrl field value
func (o *RedirectRequest) GetRedirectUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RedirectUrl
}

// GetRedirectUrlOk returns a tuple with the RedirectUrl field value
// and a boolean to check if the value has been set.
func (o *RedirectRequest) GetRedirectUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RedirectUrl, true
}

// SetRedirectUrl sets field value
func (o *RedirectRequest) SetRedirectUrl(v string) {
	o.RedirectUrl = v
}

// GetCurrency returns the Currency field value
func (o *RedirectRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *RedirectRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *RedirectRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetCountry returns the Country field value
func (o *RedirectRequest) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *RedirectRequest) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *RedirectRequest) SetCountry(v string) {
	o.Country = v
}

// GetExternalIdentifier returns the ExternalIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RedirectRequest) GetExternalIdentifier() string {
	if o == nil || IsNil(o.ExternalIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalIdentifier.Get()
}

// GetExternalIdentifierOk returns a tuple with the ExternalIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RedirectRequest) GetExternalIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalIdentifier.Get(), o.ExternalIdentifier.IsSet()
}

// HasExternalIdentifier returns a boolean if a field has been set.
func (o *RedirectRequest) HasExternalIdentifier() bool {
	if o != nil && o.ExternalIdentifier.IsSet() {
		return true
	}

	return false
}

// SetExternalIdentifier gets a reference to the given NullableString and assigns it to the ExternalIdentifier field.
func (o *RedirectRequest) SetExternalIdentifier(v string) {
	o.ExternalIdentifier.Set(&v)
}
// SetExternalIdentifierNil sets the value for ExternalIdentifier to be an explicit nil
func (o *RedirectRequest) SetExternalIdentifierNil() {
	o.ExternalIdentifier.Set(nil)
}

// UnsetExternalIdentifier ensures that no value is present for ExternalIdentifier, not even an explicit nil
func (o *RedirectRequest) UnsetExternalIdentifier() {
	o.ExternalIdentifier.Unset()
}

// GetBuyerId returns the BuyerId field value if set, zero value otherwise.
func (o *RedirectRequest) GetBuyerId() string {
	if o == nil || IsNil(o.BuyerId) {
		var ret string
		return ret
	}
	return *o.BuyerId
}

// GetBuyerIdOk returns a tuple with the BuyerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RedirectRequest) GetBuyerIdOk() (*string, bool) {
	if o == nil || IsNil(o.BuyerId) {
		return nil, false
	}
	return o.BuyerId, true
}

// HasBuyerId returns a boolean if a field has been set.
func (o *RedirectRequest) HasBuyerId() bool {
	if o != nil && !IsNil(o.BuyerId) {
		return true
	}

	return false
}

// SetBuyerId gets a reference to the given string and assigns it to the BuyerId field.
func (o *RedirectRequest) SetBuyerId(v string) {
	o.BuyerId = &v
}

// GetBuyerExternalIdentifier returns the BuyerExternalIdentifier field value if set, zero value otherwise.
func (o *RedirectRequest) GetBuyerExternalIdentifier() string {
	if o == nil || IsNil(o.BuyerExternalIdentifier) {
		var ret string
		return ret
	}
	return *o.BuyerExternalIdentifier
}

// GetBuyerExternalIdentifierOk returns a tuple with the BuyerExternalIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RedirectRequest) GetBuyerExternalIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.BuyerExternalIdentifier) {
		return nil, false
	}
	return o.BuyerExternalIdentifier, true
}

// HasBuyerExternalIdentifier returns a boolean if a field has been set.
func (o *RedirectRequest) HasBuyerExternalIdentifier() bool {
	if o != nil && !IsNil(o.BuyerExternalIdentifier) {
		return true
	}

	return false
}

// SetBuyerExternalIdentifier gets a reference to the given string and assigns it to the BuyerExternalIdentifier field.
func (o *RedirectRequest) SetBuyerExternalIdentifier(v string) {
	o.BuyerExternalIdentifier = &v
}

func (o RedirectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RedirectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["method"] = o.Method
	toSerialize["redirect_url"] = o.RedirectUrl
	toSerialize["currency"] = o.Currency
	toSerialize["country"] = o.Country
	if o.ExternalIdentifier.IsSet() {
		toSerialize["external_identifier"] = o.ExternalIdentifier.Get()
	}
	if !IsNil(o.BuyerId) {
		toSerialize["buyer_id"] = o.BuyerId
	}
	if !IsNil(o.BuyerExternalIdentifier) {
		toSerialize["buyer_external_identifier"] = o.BuyerExternalIdentifier
	}
	return toSerialize, nil
}

func (o *RedirectRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"method",
		"redirect_url",
		"currency",
		"country",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRedirectRequest := _RedirectRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRedirectRequest)

	if err != nil {
		return err
	}

	*o = RedirectRequest(varRedirectRequest)

	return err
}

type NullableRedirectRequest struct {
	value *RedirectRequest
	isSet bool
}

func (v NullableRedirectRequest) Get() *RedirectRequest {
	return v.value
}

func (v *NullableRedirectRequest) Set(val *RedirectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRedirectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRedirectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRedirectRequest(val *RedirectRequest) *NullableRedirectRequest {
	return &NullableRedirectRequest{value: val, isSet: true}
}

func (v NullableRedirectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRedirectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


