/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentServiceUpdateReportingFieldsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentServiceUpdateReportingFieldsInner{}

// PaymentServiceUpdateReportingFieldsInner A key-value pair that represents a reporting field defined in the definition for this payment service.
type PaymentServiceUpdateReportingFieldsInner struct {
	// The key of the field to set a value for.
	Key string `json:"key"`
	// The value of a field to set; you can unset optional fields by setting this to an empty string `\"\"`.
	Value string `json:"value"`
}

type _PaymentServiceUpdateReportingFieldsInner PaymentServiceUpdateReportingFieldsInner

// NewPaymentServiceUpdateReportingFieldsInner instantiates a new PaymentServiceUpdateReportingFieldsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentServiceUpdateReportingFieldsInner(key string, value string) *PaymentServiceUpdateReportingFieldsInner {
	this := PaymentServiceUpdateReportingFieldsInner{}
	this.Key = key
	this.Value = value
	return &this
}

// NewPaymentServiceUpdateReportingFieldsInnerWithDefaults instantiates a new PaymentServiceUpdateReportingFieldsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentServiceUpdateReportingFieldsInnerWithDefaults() *PaymentServiceUpdateReportingFieldsInner {
	this := PaymentServiceUpdateReportingFieldsInner{}
	return &this
}

// GetKey returns the Key field value
func (o *PaymentServiceUpdateReportingFieldsInner) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *PaymentServiceUpdateReportingFieldsInner) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *PaymentServiceUpdateReportingFieldsInner) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *PaymentServiceUpdateReportingFieldsInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *PaymentServiceUpdateReportingFieldsInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *PaymentServiceUpdateReportingFieldsInner) SetValue(v string) {
	o.Value = v
}

func (o PaymentServiceUpdateReportingFieldsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentServiceUpdateReportingFieldsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *PaymentServiceUpdateReportingFieldsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentServiceUpdateReportingFieldsInner := _PaymentServiceUpdateReportingFieldsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentServiceUpdateReportingFieldsInner)

	if err != nil {
		return err
	}

	*o = PaymentServiceUpdateReportingFieldsInner(varPaymentServiceUpdateReportingFieldsInner)

	return err
}

type NullablePaymentServiceUpdateReportingFieldsInner struct {
	value *PaymentServiceUpdateReportingFieldsInner
	isSet bool
}

func (v NullablePaymentServiceUpdateReportingFieldsInner) Get() *PaymentServiceUpdateReportingFieldsInner {
	return v.value
}

func (v *NullablePaymentServiceUpdateReportingFieldsInner) Set(val *PaymentServiceUpdateReportingFieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentServiceUpdateReportingFieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentServiceUpdateReportingFieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentServiceUpdateReportingFieldsInner(val *PaymentServiceUpdateReportingFieldsInner) *NullablePaymentServiceUpdateReportingFieldsInner {
	return &NullablePaymentServiceUpdateReportingFieldsInner{value: val, isSet: true}
}

func (v NullablePaymentServiceUpdateReportingFieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentServiceUpdateReportingFieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


