/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentServiceRequestFieldsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentServiceRequestFieldsInner{}

// PaymentServiceRequestFieldsInner A key-value pair that represents a field defined in the definition for this payment service.
type PaymentServiceRequestFieldsInner struct {
	// The key of the field to set a value for.
	Key string `json:"key"`
	// The value of a field to set.
	Value string `json:"value"`
}

type _PaymentServiceRequestFieldsInner PaymentServiceRequestFieldsInner

// NewPaymentServiceRequestFieldsInner instantiates a new PaymentServiceRequestFieldsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentServiceRequestFieldsInner(key string, value string) *PaymentServiceRequestFieldsInner {
	this := PaymentServiceRequestFieldsInner{}
	this.Key = key
	this.Value = value
	return &this
}

// NewPaymentServiceRequestFieldsInnerWithDefaults instantiates a new PaymentServiceRequestFieldsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentServiceRequestFieldsInnerWithDefaults() *PaymentServiceRequestFieldsInner {
	this := PaymentServiceRequestFieldsInner{}
	return &this
}

// GetKey returns the Key field value
func (o *PaymentServiceRequestFieldsInner) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *PaymentServiceRequestFieldsInner) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *PaymentServiceRequestFieldsInner) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *PaymentServiceRequestFieldsInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *PaymentServiceRequestFieldsInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *PaymentServiceRequestFieldsInner) SetValue(v string) {
	o.Value = v
}

func (o PaymentServiceRequestFieldsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentServiceRequestFieldsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *PaymentServiceRequestFieldsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentServiceRequestFieldsInner := _PaymentServiceRequestFieldsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentServiceRequestFieldsInner)

	if err != nil {
		return err
	}

	*o = PaymentServiceRequestFieldsInner(varPaymentServiceRequestFieldsInner)

	return err
}

type NullablePaymentServiceRequestFieldsInner struct {
	value *PaymentServiceRequestFieldsInner
	isSet bool
}

func (v NullablePaymentServiceRequestFieldsInner) Get() *PaymentServiceRequestFieldsInner {
	return v.value
}

func (v *NullablePaymentServiceRequestFieldsInner) Set(val *PaymentServiceRequestFieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentServiceRequestFieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentServiceRequestFieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentServiceRequestFieldsInner(val *PaymentServiceRequestFieldsInner) *NullablePaymentServiceRequestFieldsInner {
	return &NullablePaymentServiceRequestFieldsInner{value: val, isSet: true}
}

func (v NullablePaymentServiceRequestFieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentServiceRequestFieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


