/*
Gr4vy API

Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.

API version: 1.1.0-beta
Contact: code@gr4vy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments{}

// ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments Comments to merchant or beneficiary written by customer.
type ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments struct {
	// Comments the customer left to the merchant.
	UserCommentsToMerchant NullableString `json:"user_comments_to_merchant,omitempty"`
	// Comments the customer left to the beneficiary of the purchase made.
	MessageToBeneficiary NullableString `json:"message_to_beneficiary,omitempty"`
	// Comments by the merchant.
	MerchantComments NullableString `json:"merchant_comments,omitempty"`
}

// NewConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments instantiates a new ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments() *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments {
	this := ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments{}
	return &this
}

// NewConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerCommentsWithDefaults instantiates a new ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerCommentsWithDefaults() *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments {
	this := ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments{}
	return &this
}

// GetUserCommentsToMerchant returns the UserCommentsToMerchant field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) GetUserCommentsToMerchant() string {
	if o == nil || IsNil(o.UserCommentsToMerchant.Get()) {
		var ret string
		return ret
	}
	return *o.UserCommentsToMerchant.Get()
}

// GetUserCommentsToMerchantOk returns a tuple with the UserCommentsToMerchant field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) GetUserCommentsToMerchantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserCommentsToMerchant.Get(), o.UserCommentsToMerchant.IsSet()
}

// HasUserCommentsToMerchant returns a boolean if a field has been set.
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) HasUserCommentsToMerchant() bool {
	if o != nil && o.UserCommentsToMerchant.IsSet() {
		return true
	}

	return false
}

// SetUserCommentsToMerchant gets a reference to the given NullableString and assigns it to the UserCommentsToMerchant field.
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) SetUserCommentsToMerchant(v string) {
	o.UserCommentsToMerchant.Set(&v)
}
// SetUserCommentsToMerchantNil sets the value for UserCommentsToMerchant to be an explicit nil
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) SetUserCommentsToMerchantNil() {
	o.UserCommentsToMerchant.Set(nil)
}

// UnsetUserCommentsToMerchant ensures that no value is present for UserCommentsToMerchant, not even an explicit nil
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) UnsetUserCommentsToMerchant() {
	o.UserCommentsToMerchant.Unset()
}

// GetMessageToBeneficiary returns the MessageToBeneficiary field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) GetMessageToBeneficiary() string {
	if o == nil || IsNil(o.MessageToBeneficiary.Get()) {
		var ret string
		return ret
	}
	return *o.MessageToBeneficiary.Get()
}

// GetMessageToBeneficiaryOk returns a tuple with the MessageToBeneficiary field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) GetMessageToBeneficiaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MessageToBeneficiary.Get(), o.MessageToBeneficiary.IsSet()
}

// HasMessageToBeneficiary returns a boolean if a field has been set.
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) HasMessageToBeneficiary() bool {
	if o != nil && o.MessageToBeneficiary.IsSet() {
		return true
	}

	return false
}

// SetMessageToBeneficiary gets a reference to the given NullableString and assigns it to the MessageToBeneficiary field.
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) SetMessageToBeneficiary(v string) {
	o.MessageToBeneficiary.Set(&v)
}
// SetMessageToBeneficiaryNil sets the value for MessageToBeneficiary to be an explicit nil
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) SetMessageToBeneficiaryNil() {
	o.MessageToBeneficiary.Set(nil)
}

// UnsetMessageToBeneficiary ensures that no value is present for MessageToBeneficiary, not even an explicit nil
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) UnsetMessageToBeneficiary() {
	o.MessageToBeneficiary.Unset()
}

// GetMerchantComments returns the MerchantComments field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) GetMerchantComments() string {
	if o == nil || IsNil(o.MerchantComments.Get()) {
		var ret string
		return ret
	}
	return *o.MerchantComments.Get()
}

// GetMerchantCommentsOk returns a tuple with the MerchantComments field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) GetMerchantCommentsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MerchantComments.Get(), o.MerchantComments.IsSet()
}

// HasMerchantComments returns a boolean if a field has been set.
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) HasMerchantComments() bool {
	if o != nil && o.MerchantComments.IsSet() {
		return true
	}

	return false
}

// SetMerchantComments gets a reference to the given NullableString and assigns it to the MerchantComments field.
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) SetMerchantComments(v string) {
	o.MerchantComments.Set(&v)
}
// SetMerchantCommentsNil sets the value for MerchantComments to be an explicit nil
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) SetMerchantCommentsNil() {
	o.MerchantComments.Set(nil)
}

// UnsetMerchantComments ensures that no value is present for MerchantComments, not even an explicit nil
func (o *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) UnsetMerchantComments() {
	o.MerchantComments.Unset()
}

func (o ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.UserCommentsToMerchant.IsSet() {
		toSerialize["user_comments_to_merchant"] = o.UserCommentsToMerchant.Get()
	}
	if o.MessageToBeneficiary.IsSet() {
		toSerialize["message_to_beneficiary"] = o.MessageToBeneficiary.Get()
	}
	if o.MerchantComments.IsSet() {
		toSerialize["merchant_comments"] = o.MerchantComments.Get()
	}
	return toSerialize, nil
}

type NullableConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments struct {
	value *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments
	isSet bool
}

func (v NullableConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) Get() *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments {
	return v.value
}

func (v *NullableConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) Set(val *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments(val *ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) *NullableConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments {
	return &NullableConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments{value: val, isSet: true}
}

func (v NullableConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


